-- MySQL Script generated by MySQL Workbench
-- 04/21/14 11:05:51
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema needledb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `needledb` ;
CREATE SCHEMA IF NOT EXISTS `needledb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `needledb` ;

-- -----------------------------------------------------
-- Table `needles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `needles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `needles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) UNIQUE NULL,
  `needle_start` VARCHAR(32) NULL,
  `needle_end` VARCHAR(32) NULL,
  `created` DATETIME NULL,
  `created_by` VARCHAR(256) NULL,
  `modified` DATETIME NULL,
  `modified_by` VARCHAR(256) NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
COMMENT = 'Stores the needle to be found';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `urls`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `urls` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `urls` (
  `id` INT NOT NULL AUTO_INCREMENT,
   `name` VARCHAR(256) UNIQUE NULL, 
  `url` VARCHAR(1028) NULL,
  `created` DATETIME NULL,
  `created_by` VARCHAR(256) NULL,
  `modified` DATETIME NULL,
  `modified_by` VARCHAR(256) NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
COMMENT = 'Store the URL information';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `haystacks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `haystacks` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `haystacks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `needle_id` INT NOT NULL,
  `url_id` INT NULL,
  `haystack` TEXT NULL,
  `needle_found` VARCHAR(256) NULL,
  `created` DATETIME NULL,
  `created_by` VARCHAR(256) NULL,
  `modified` DATETIME NULL,
  `modified_by` VARCHAR(256) NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
COMMENT = 'Stores the haystack for each session and any needle if found';

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
